### PR TITLE
Fix operation_id variable shadowing in Rust generator

### PR DESCRIPTION
**Pull request by walidcavelius**
## Summary

`ListRUMOperationStrongLinks` (moving to GA as part of DataDog/datadog-api-spec#6240) is the first operation in the entire spec to have a parameter literally named `operation_id`. That collides with an internal variable of the same name that `.generator/src/generator/templates/api.j2` declares for every operation to resolve the per-operation server host:

```
let operation_id = "v2.list_rum_operation_strong_links";
...
let operation_id = params.operation_id;   // unboxes the real query param, Option<String>
...
local_configuration.get_operation_host(operation_id)  // now gets Option<String>, not &str
```

Rust shadowing means the second `let` silently wins, so `get_operation_host` receives an `Option<String>` where it expects `&str`:

```
error[E0308]: mismatched types
   --> src/datadogV2/api/api_rum_operations.rs:973:52
    |
973 |             local_configuration.get_operation_host(operation_id));
    |                                 ------------------ ^^^^^^^^^^^^ expected `&str`, found `Option<String>`
```

This has been a latent hazard since `operation_id`-based host resolution was introduced in #15 (Feb 2024) — it just never had a colliding parameter name to trigger it until now.

## Fix

Rename the internal literal to `local_operation_id`, matching the `local_` prefix convention every other generator-internal variable in this function already follows (`local_configuration`, `local_client`, `local_uri_str`, `local_req_builder`, `local_query_param`, `local_error`). This is the one internal variable that didn't follow that convention.

The wire contract is unaffected — the query parameter is still sent as `operation_id` (the key comes from a separate literal in the template, not from the Rust variable name).

## Verification

- Reproduced the failure by regenerating the client from the actual bundled spec in DataDog/datadog-api-spec#6240.
- Applied the fix and regenerated the full client (v1 + v2, ~180 API files).
- Diffed every changed file byte-for-byte against the pre-fix output after normalizing `local_operation_id` back to `operation_id`: the only difference anywhere in the generated codebase is that token rename — nothing else changed.
- Confirmed no parameter anywhere in the spec is named `local_operation_id`, `local_configuration`, `local_client`, etc., so this can't reintroduce the same collision.

## Test plan

- [ ] CI regenerates and compiles `api_rum_operations.rs` (and all other operations) successfully once DataDog/datadog-api-spec#6240 merges

### CODE REVIEW

**Review by jack-edmonds-dd — APPROVED** [review]
My Claude had the same idea.
